---
title: "Help with R"
author: "Nicolas Ballier"
date: "4/30/2020"
output: html_document
---


## R Documentation-------
Learn to make the most of R built-in help functions:

Nice post for beginners :<https://aosmith.rbind.io/2020/04/28/r-documentation/>

## CRAN documentation 
https://cran.r-project.org/

<https://cran.r-project.org/web/packages/quanteda/index.html>

## vignettes
browseVignettes()

## exploring help
ls("package:quanteda")
help(package = "quanteda")

library(quanteda)
data()

## more elaborate papers (R Journal)

# blogs
<https://www.r-bloggers.com/>

# quanteda

## STACK OVERFLOW
Get an answer

Asking a clear, detailed question makes it more likely you will get an answer.

Read on for the 3 easy steps.
alt_text
Step 1 - Explain your problem

Yes, skip writing the title for now. In the body, describe what you were trying to do. Describe what results you expected to see and what results you actually saw. Include any error messages you received.
Step 2 - Provide more details and “Show me your code”

Tell us what you’ve tried and tell us what you found (on this site or elsewhere) when you did your own research and why the solution(s) didn’t meet your needs. Include enough of your actual code so people can run it themselves, identify the problem, and provide you a solution (in other words, “Show me your code”).

The more information you can put in the question, the more likely you will be to get an answer.
Step 3 - Write a title that summarizes the problem

Now that you’ve summarized your problem and everything you’ve tried, it should be easier to write a title for your question. People scan titles to figure out which ones they want to answer.

Make your question more likely to get answered by using these best practices for titles:

    Make it a question. An easy way to make sure it reads like a question is to start your title with “what”, “where”, “when”, “why” or “how.”
    Include the action you want. Are you looking for a “fix”, are you looking to “prevent” something from happening, are you looking to “compare”, do you want to “access” something. If you aren’t sure about the action, look at what you wrote about the results you wanted from your code.
    Look at your title. If someone else read the title, would they know what you needed help with? If not, think about if you were asking someone sitting next to you for help - what would you tell them you needed help with?


<https://www.youtube.com/watch?v=vZ63ndKIYMo&utm_source=Iterable&utm_medium=email&utm_campaign=pqa-engagement&utm_content=newuser-email02>


